export const questionsData = [
    {
        question: 'Для кого вы ищете учебное заведение?',
        name: 'initiator',
        answerType: 'radio',
        variants: [ 'Себе', 'Супругу/супруге', 'Родственнику', 'Коллеге', 'Ребенку', 'Другое'],
        id: 1,
    },
    {
        question: 'В каком городе планируете поступать?',
        name: 'cities',
        answerType: 'select',
        variants: [ 'Санкт-Петербург', 'Москва', 'Новосибирск', 'Нижний новгород', 'Ростов-на-Дону', 'Казань', 'Челябинск', 'Омск', 'Краснодар', 'Уфа', 'Пермь', 'Другой' ],
        id: 2,
    },
    {
        question: 'Какое образование уже есть?',
        name: 'currentEducation',
        answerType: 'radio',
        variants: [ '9 классов', '11 классов', 'Училище', 'Колледж/техникум', 'Неоконченное высшее', 'Высшее' ],
        id: 3,
    },
    {
        question: 'Куда планируете поступать?',
        name: 'educationTargetType',
        answerType: 'radio',
        variants: [ 'Вуз', 'Колледж/техникум', 'Училище' ],
        id: 4,
    },
    {
        question: 'Какую форму обучения предпочитаете?',
        name: 'learningForm',
        answerType: 'radio',
        variants: [ 'Очную', 'Заочную', 'Дистанционную' ],
        id: 5,
    },
    {
        question: 'Рассматриваете платное обучение?',
        name: 'paidEducationAllowedType',
        answerType: 'radio',
        variants: [ 'Нет, только бюджет', 'Да, планирую учиться платно', 'Возможны оба варианта' ],
        id: 6,
    },
    {
        question: 'Какая специальность интересует?',
        name: 'educationSpecialityType',
        answerType: 'select',
        variants: [ 'Экономика', 'Философия', 'Социология', 'Юриспруденция' ],
        id: 7,
    },
    {
        question: 'Как скоро планируете поступать?',
        name: 'howManyToAdmission',
        answerType: 'radio',
        variants: [ 'Как можно быстрее', 'Месяц', 'Квартал', 'Полгода', 'Год' ],
        id: 8,
    },
];